### ISSUE TITLE
My apps can’t be removed 

### ISSUE THREAD

**Issue by Mac1962** [builtbybel/bloatbox#11]
On the latest version bloatbox this list of apps can’t be removed do you know why they can’t 
Be removed.
![92971B71-38E8-44B7-9989-B8CEF42C5573](https://user-images.githubusercontent.com/31389715/88540501-f791cf80-d00a-11ea-89fa-5e031b5bb4f0.jpeg)

**Comment by Belim** [comment]
this is normal because some app packages depend on other packages, e.g. Microsoft.UI.Xaml.2.3 cannot be removed because the Windows Calculator depends on it. The Microsoft.Windows.CallingShellApp and Microsoft.Windows.Search are part of Windows and could possibly be disabled via the Windows features. this also affects all other packages where uninstallation failed
