### ISSUE TITLE
After remove all Microsoft apps...

### ISSUE THREAD

**Issue by BillyVa** [builtbybel/bloatbox#12]
my computer not running all my programms

If possible an undo function maybe or a warning

Or exclude some apps from uninstall for example NET.framework etc.

Thank you

**Comment by rodrigomologni** [comment]
I would like to know too. My apps were uninstalled (or disabled) even without me clicking Uninstall. I only moved the apps to Remove Apps. Now I have to start the Windows Calculator on the Microsoft Store whenever I need it.

**Comment by Belim** [comment]
@BillyVa 
> Or exclude some apps from uninstall for example NET.framework etc.

this is a basic function of the app. Just leave the apps you do not want to remove in the left panel. System apps as .Net Framework, Edge etc. will not be removed anyway. The system can not be harmed by this.


@rodrigomologni 
> I would like to know too. My apps were uninstalled (or disabled) even without me clicking Uninstall. I only moved the apps to Remove Apps.

No, this is NOT possible! you must have clicked the uninstall button

> Now I have to start the Windows Calculator on the Microsoft Store whenever I need it.

Nothing is lost. E.g. to re-install the Calculator app, just open the PowerShell and type
`Get-AppxPackage -allusers *windowscalculator* | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register “$($_.InstallLocation)\AppXManifest.xml”}`

**Comment by rodrigomologni** [comment]
Hi @BillyVa ! Thank you for answering me.

> No, this is NOT possible! you must have clicked the uninstall button

Actually, I clicked Uninstall. However, as I remember, there was only one app in Remove Apps when I clicked the button. Nonetheless, all of my apps have been removed.

> Nothing is lost. E.g. to re-install the Calculator app, just open the PowerShell and type
`Get-AppxPackage -allusers *windowscalculator* | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}`

I'm glad to know that the process is reversible. I ran your script, but...

![image](https://user-images.githubusercontent.com/1608652/88864698-1e533000-d1dc-11ea-9ff4-3d496f4a97b6.png)

**Comment by Belim** [comment]
please start the PowerShell as administrator and run again
`Get-AppxPackage -allusers *windowscalculator* | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}`

**Comment by rodrigomologni** [comment]
Hi @Belim ! Same problem for both. 😕

**Comment by rodrigomologni** [comment]
@Belim, yes, sorry!

```
Get-AppXPackage : The trust relationship between this workstation and the primary domain failed. (Exception from HRESULT: 0x800706FD)
At line:1 char:1
+ Get-AppxPackage -allusers *windowscalculator* | Foreach {Add-AppxPack ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AppxPackage], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.Windows.Appx.PackageManager.Commands.GetAppxPackageCommand 
```

I found a likely solution in https://support.microsoft.com/en-us/help/2771040/the-trust-relationship-between-this-workstation-and-the-primary-domain. However, I can't test this because I don't have access to the Administrator account.

![image](https://user-images.githubusercontent.com/1608652/89031429-e1d12280-d308-11ea-9a7b-a9cc07904ab8.png)

Translation: "After leaving the domain, you will need to know the password for your local administrator account to logon to your computer."

**Comment by Belim** [comment]
It is in fact so that leaving the Domain <> Workgroup and re-entering the domain can help.

So the administrative rights are probably restricted and shot for whatever reason, even though your powershell console thinks it runs as administrator. I can't help you either. You probably need to contact the administrator. Tell him you're not doing anything bad and buy him a coffee :grin:

**Comment by rodrigomologni** [comment]
@Belim thank you for your help! :v::coffee:
